[package]
name = "zero2prod"
version = "0.1.0"
edition = "2024"
license = "MIT"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "zero2prod"

[dependencies]
axum = "0.8.4"
tokio = { version = "1.47.1", features = ["full"] }

[dev-dependencies]
reqwest = "0.12.23"
